sudo: required

env:
 gloval:
  - DOCKER_USER=audwns27
  - DOCKER_PASS=mypassword

language: python

services:
 - docker

before_install:
 - echo "Hello World"

script:
 - cd identidock
 - docker build -t identidock .
 - docker run -e ENV=TEST identidock
 - docker-compose up -d

after_success:
 - echo "Test sucess!"

notification:
 eamil:
  - audwns392@naver.com
 
