sudo: required

language: python

services:
 - docker

before_install:
 - echo "Hello World"

script:
 - docker-compose up -d

after_success:
 - echo "test sucess!"

notification:
 eamil:
  - audwns392@naver.com

